services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - S3_BUCKET=your-s3-bucket
      - DDB_TABLE=your-dynamodb-table
      - ML_SERVICE_URL=http://ml_service:8000/caption
      - SECRET_KEY=supersecretkey
    depends_on:
      - ml_service
  ml_service:
    build: ./ml_service
    ports:
      - "8001:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
